name: Code Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write  # This gives permission to comment on PRs
      contents: read  # Basic read permission for the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Run Code Review
      id: review
      run: |
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        review_output=$(dotnet run --project ./TestAppAICodeReview.csproj --review-code)
        echo "$review_output"
        # You can include logic to output the review results to a file or variable

    - name: Post Review as PR Comment
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
        -d '{"body": "'"$review_output"'"}'